FROM ftnginx

ADD phpmyadmin/ /usr/share/nginx/html

# SQL DB only :
ADD mariadb.cnf /etc/my.cnf.d/mariadb-server.cnf

RUN apk update \
 && apk add mariadb mariadb-common mariadb-client \
 && chown mysql /var/lib/mysql \
 && mkdir -p /run/mysqld \
 ;

RUN mariadb-install-db -u root;

CMD php-fpm7 \
 && nginx \
 && mysqld -u root \
 ;
