apiVersion: v1
kind: Service
metadata:
  name: ftnginx-svc
spec:
  type: LoadBalancer
  selector:
    app: ftnginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ftnginx-dpl
  labels:
    app: ftnginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftnginx
  template:
    metadata:
      labels:
        app: ftnginx
    spec:
      containers:
      - name: ftnginx-ctn
        image: ft_nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
