apiVersion: v1
kind: Service
metadata:
  name: ftnginx-svc
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ftnginx-dpl
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: ftnginx-ctn
        image: ft_nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
      tolerations:
      - key: "node.kubernetes.io/disk-pressure"
        effect: NoSchedule
        operator: Exists

