apiVersion: v1
kind: Service
metadata:
  name: ftnginx
spec:
  type: NodePort
  selector:
    app: ftnginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ftnginx
  labels:
    app: ftnginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftnginx
  template:
    metadata:
      labels:
        app: ftnginx
    spec:
      containers:
      - name: ftnginx
        image: ft_nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
      tolerations:
      - key: "node.kubernetes.io/disk-pressure"
        effect: NoSchedule
        operator: Exists

