FROM alpine

RUN apk update \
 && apk add nginx && mkdir /run/nginx \
 && apk add php7 php7-fpm php7-mysqli php7-iconv php7-mbstring php7-json php7-session \
 ;

ADD files/ /

EXPOSE 80

CMD php-fpm7 \
 && nginx -g 'daemon off;' \
 ;
