FROM alpine

RUN apk update \
 && apk add mariadb mariadb-common mariadb-client \
 && chown mysql /var/lib/mysql \
 && mkdir -p /run/mysqld \
 ;

ADD mariadb.cnf /etc/my.cnf.d/mariadb-server.cnf

RUN mariadb-install-db -u root;

EXPOSE 3306

CMD mysqld -u root;
