apiVersion: v1
kind: Service
metadata:
  name: ftmysql
spec:
  type: ClusterIP
  selector:
    app: ftmysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftmysql
  labels:
    app: ftmysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ftmysql
  labels:
    app: ftmysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftmysql
  template:
    metadata:
      labels:
        app: ftmysql
    spec:
      volumes:
      - name: mysqldb
        persistentVolumeClaim: 
         claimName: ftmysql
      containers:
      - name: ftmysql
        image: ftmysql
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysqldb
          mountPath: /var/lib/mysql
