FROM alpine

RUN apk update \
 && apk add grafana --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/ \
 ;

ADD sources.yaml	/usr/share/grafana/conf/provisioning/datasources/sources.yaml
ADD config.yaml 	/usr/share/grafana/conf/provisioning/dashboards/config.yaml
ADD dashboards/ 	/usr/share/grafana/conf/provisioning/dashboards/mine/

EXPOSE 3000

CMD grafana-server --homepath "/usr/share/grafana";
