apiVersion: v1
kind: Service
metadata:
  name: ftgrafana
  annotations:
    metallb.universe.tf/allow-shared-ip: ftservices
spec:
  type: LoadBalancer
  selector:
    app: ftgrafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ftgrafana
  labels:
    app: ftgrafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftgrafana
  template:
    metadata:
      labels:
        app: ftgrafana
    spec:
      containers:
      - name: ftgrafana
        image: ftgrafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
