apiVersion: 1
datasources:
- name: InfluxDB
  type: influxdb
  access: proxy
  database: telegraf
  isDefault: true
  user: user42
  secureJsonData:
    password: user42
  url: http://ftinfluxdb:8086
  