apiVersion: v1
kind: Service
metadata:
  name: ftinfluxdb
  annotations:
    metallb.universe.tf/allow-shared-ip: ftservices
spec:
  type: LoadBalancer
  selector:
    app: ftinfluxdb
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ftinfluxdb
  labels:
    app: ftinfluxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftinfluxdb
  template:
    metadata:
      labels:
        app: ftinfluxdb
    spec:
      containers:
      - name: ftinfluxdb
        image: ftinfluxdb
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
