FROM alpine

RUN apk update \
 && apk add vsftpd && mkdir -p /run/vsftpd \
 && adduser -D user42 && echo "user42:user42" | chpasswd \
 ;

ADD files/ /

RUN : \
 && mkdir -p /home/user42/ftp/files \
 && chown "nobody:nogroup" /home/user42/ftp \
 && chown "user42:user42"  /home/user42/ftp/files \
 && chmod a-w /home/user42/ftp \
 ;

EXPOSE 21 20 21101 21100

CMD /usr/sbin/vsftpd /etc/vsftpd/my_vsftpd.conf
