FROM alpine

RUN apk update \
 && apk add vsftpd && mkdir -p /run/vsftpd \
 && adduser -D user42 && echo "user42:user42" | chpasswd \
 ;

ADD files/ /

EXPOSE 21 20 21101 21100

CMD /usr/sbin/vsftpd /etc/vsftpd/my_vsftpd.conf
