apiVersion: v1
kind: Service
metadata:
  name: ftwordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: ftservices
spec:
  type: LoadBalancer
  selector:
    app: ftwordpress
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ftwordpress
  labels:
    app: ftwordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftwordpress
  template:
    metadata:
      labels:
        app: ftwordpress
    spec:
      containers:
      - name: ftwordpress
        image: ftwordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 443
